### ISSUE TITLE
Add FileHelpers

### ISSUE THREAD

**Issue by JoshClose** [joelverhagen/NCsvPerf#13]
https://www.nuget.org/packages/FileHelpers/
https://www.filehelpers.net/

This library is actually the reason I created CsvHelper back in 2009. It was the gold standard, but I didn't like the API.

**Comment by JoshClose** [comment]
Requires objects to be created.

**Comment by joelverhagen** [comment]
Done with https://github.com/joelverhagen/NCsvPerf/pull/38.
