### ISSUE TITLE
Add LinqToCsv

### ISSUE THREAD

**Issue by JoshClose** [joelverhagen/NCsvPerf#20]
https://www.codeproject.com/Articles/25133/LINQ-to-CSV-library
https://www.nuget.org/packages/LinqToCsv

Recommended on StackOverflow.

**Comment by JoshClose** [comment]
Code is based off of section "Reading Raw Data Rows" https://www.codeproject.com/Articles/25133/LINQ-to-CSV-library#ReadingRawDataRows

**Comment by JoshClose** [comment]
Added pull request for this. https://github.com/joelverhagen/NCsvPerf/pull/21

**Comment by joelverhagen** [comment]
Thanks Josh! Done.
