### ISSUE TITLE
Add-TxtCsvHelper

### ISSUE THREAD

**Issue by camdrudge** [joelverhagen/NCsvPerf#31]
Please add TxtCsvHelper to test

**Comment by joelverhagen** [comment]
Hey @camdrudge, is this something you'd be able to provide a PR for? Take a look at some of the [closed PRs](https://github.com/joelverhagen/NCsvPerf/pulls?q=is%3Apr+is%3Aclosed) for examples.

If you provide the PR, I'm happy to run the benchmark again and update my blog post.

**Comment by joelverhagen** [comment]
Fixed with https://github.com/joelverhagen/NCsvPerf/pull/32.
