### ISSUE TITLE
Any prevision to update blog post?

### ISSUE THREAD

**Issue by leandromoh** [joelverhagen/NCsvPerf#37]
Latest update is described 2021-06-16 in [fastest-net-csv-parsers post](https://www.joelverhagen.com/blog/2020/12/fastest-net-csv-parsers)

3 libs were added/adjusted (AFAIK):
- Use private version of CommonLibrary.NET
- #30
- #32

**Comment by joelverhagen** [comment]
Hey @leandromoh, apologies on the delay. I just got back from vacation and have a rather hectic season at work. I have not forgotten about this and will work on this update as soon as I can.

The update is very manual and the broken up in time (the benchmarks take over an hour to run) so it's not something I can knock out most evenings.

**Comment by joelverhagen** [comment]
Done. RecordParser is 3rd place. TxtCsvHelper is 9th place.

**Comment by leandromoh** [comment]
@joelverhagen Thank you!
