### ISSUE TITLE
Add ML.NET MLContext.Data.LoadFromTextFile<T>

### ISSUE THREAD

**Issue by jzabroski** [joelverhagen/NCsvPerf#5]
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net#load-data-from-a-single-file

> ```c#
> public class HousingData
> {
>     [LoadColumn(0)]
>     public float Size { get; set; }
> 
>     [LoadColumn(1, 3)]
>     [VectorType(3)]
>     public float[] HistoricalPrices { get; set; }
> 
>     [LoadColumn(4)]
>     [ColumnName("Label")]
>     public float CurrentPrice { get; set; }
> }
> //Create MLContext
> MLContext mlContext = new MLContext();
> 
> //Load Data
> IDataView data = mlContext.Data.LoadFromTextFile<HousingData>("my-data-file.csv", separatorChar: ',', hasHeader: true);
> ```

**Comment by jzabroski** [comment]
It would be cool to see how Microsoft's machine learning code performs here.

**Comment by joelverhagen** [comment]
I played around with this one a bit and I agree it would be awesome to compare the performance. However, my current benchmark relies on the parsing library to give each row's data in unmapped form (e.g. `string[]`). It looks like this library does have that granular of an API -- or at least not available in the `public` surface area.

This would be a cool library to test if and when I add a higher level "data mapping" benchmark. I'll leave this issue open for that time.

**Comment by jzabroski** [comment]
Seems do-able to add that benchmark.  I'll give it a shot if that's ok with you.

**Comment by joelverhagen** [comment]
Done with https://github.com/joelverhagen/NCsvPerf/pull/38.
