### ISSUE TITLE
Sep library now supports parallel processing

### ISSUE THREAD

**Issue by burnchar** [joelverhagen/NCsvPerf#65]
RecordParser is no longer the only parallel CSV library.

> 🌪️ Multi-threaded - unparalleled speed with highly efficient parallel CSV parsing that is [up to 35x faster than CsvHelper]

 Please add Sep tests with parallel support. I am curious if it can dethrone RecordParser!

**Comment by joelverhagen** [comment]
@nietras already submitted a PR.
https://github.com/joelverhagen/NCsvPerf/pull/61

I just haven't gotten around to re-running the benchmarks and updating the blog. But based on his own runs (https://github.com/joelverhagen/NCsvPerf/pull/64) it's looking really good!

**Comment by nietras** [comment]
@burnchar thanks for paying attention, I have benched against RecordParser and Sep is definitely faster. I had hoped to blog about the release but occupied by other matters and experiments. Server GC is your friend!

**Comment by burnchar** [comment]
> @burnchar thanks for paying attention, I have benched against RecordParser and Sep is definitely faster. I had hoped to blog about the release but occupied by other matters and experiments. Server GC is your friend!

I was not paying enough attention to notice that you had already sent a PR, but thank you both for your good work!
Writing high-performance libraries helps both the community and even the environment, and researching and sharing performance comparisons of those libraries helps get people to actually use them.

**Comment by joelverhagen** [comment]
Updated the blog! https://www.joelverhagen.com/blog/2020/12/fastest-net-csv-parsers

**Comment by burnchar** [comment]
Thank you for your updated benchmarks, and for your work on NuGet.
